// Generated by gencpp from file era_gazebo/SceneBBoxResponse.msg
// DO NOT EDIT!


#ifndef ERA_GAZEBO_MESSAGE_SCENEBBOXRESPONSE_H
#define ERA_GAZEBO_MESSAGE_SCENEBBOXRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace era_gazebo
{
template <class ContainerAllocator>
struct SceneBBoxResponse_
{
  typedef SceneBBoxResponse_<ContainerAllocator> Type;

  SceneBBoxResponse_()
    {
    }
  SceneBBoxResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::era_gazebo::SceneBBoxResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::era_gazebo::SceneBBoxResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SceneBBoxResponse_

typedef ::era_gazebo::SceneBBoxResponse_<std::allocator<void> > SceneBBoxResponse;

typedef boost::shared_ptr< ::era_gazebo::SceneBBoxResponse > SceneBBoxResponsePtr;
typedef boost::shared_ptr< ::era_gazebo::SceneBBoxResponse const> SceneBBoxResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::era_gazebo::SceneBBoxResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::era_gazebo::SceneBBoxResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace era_gazebo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::era_gazebo::SceneBBoxResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::era_gazebo::SceneBBoxResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::era_gazebo::SceneBBoxResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::era_gazebo::SceneBBoxResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::era_gazebo::SceneBBoxResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::era_gazebo::SceneBBoxResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::era_gazebo::SceneBBoxResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::era_gazebo::SceneBBoxResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::era_gazebo::SceneBBoxResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "era_gazebo/SceneBBoxResponse";
  }

  static const char* value(const ::era_gazebo::SceneBBoxResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::era_gazebo::SceneBBoxResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"\n"
;
  }

  static const char* value(const ::era_gazebo::SceneBBoxResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::era_gazebo::SceneBBoxResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SceneBBoxResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::era_gazebo::SceneBBoxResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::era_gazebo::SceneBBoxResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ERA_GAZEBO_MESSAGE_SCENEBBOXRESPONSE_H
