// Generated by gencpp from file era_gazebo/SceneBBox.msg
// DO NOT EDIT!


#ifndef ERA_GAZEBO_MESSAGE_SCENEBBOX_H
#define ERA_GAZEBO_MESSAGE_SCENEBBOX_H

#include <ros/service_traits.h>


#include <era_gazebo/SceneBBoxRequest.h>
#include <era_gazebo/SceneBBoxResponse.h>


namespace era_gazebo
{

struct SceneBBox
{

typedef SceneBBoxRequest Request;
typedef SceneBBoxResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SceneBBox
} // namespace era_gazebo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::era_gazebo::SceneBBox > {
  static const char* value()
  {
    return "dd321c86fe9be2b64c0490217178f7cc";
  }

  static const char* value(const ::era_gazebo::SceneBBox&) { return value(); }
};

template<>
struct DataType< ::era_gazebo::SceneBBox > {
  static const char* value()
  {
    return "era_gazebo/SceneBBox";
  }

  static const char* value(const ::era_gazebo::SceneBBox&) { return value(); }
};


// service_traits::MD5Sum< ::era_gazebo::SceneBBoxRequest> should match
// service_traits::MD5Sum< ::era_gazebo::SceneBBox >
template<>
struct MD5Sum< ::era_gazebo::SceneBBoxRequest>
{
  static const char* value()
  {
    return MD5Sum< ::era_gazebo::SceneBBox >::value();
  }
  static const char* value(const ::era_gazebo::SceneBBoxRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::era_gazebo::SceneBBoxRequest> should match
// service_traits::DataType< ::era_gazebo::SceneBBox >
template<>
struct DataType< ::era_gazebo::SceneBBoxRequest>
{
  static const char* value()
  {
    return DataType< ::era_gazebo::SceneBBox >::value();
  }
  static const char* value(const ::era_gazebo::SceneBBoxRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::era_gazebo::SceneBBoxResponse> should match
// service_traits::MD5Sum< ::era_gazebo::SceneBBox >
template<>
struct MD5Sum< ::era_gazebo::SceneBBoxResponse>
{
  static const char* value()
  {
    return MD5Sum< ::era_gazebo::SceneBBox >::value();
  }
  static const char* value(const ::era_gazebo::SceneBBoxResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::era_gazebo::SceneBBoxResponse> should match
// service_traits::DataType< ::era_gazebo::SceneBBox >
template<>
struct DataType< ::era_gazebo::SceneBBoxResponse>
{
  static const char* value()
  {
    return DataType< ::era_gazebo::SceneBBox >::value();
  }
  static const char* value(const ::era_gazebo::SceneBBoxResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ERA_GAZEBO_MESSAGE_SCENEBBOX_H
