global_frame: r1/odom
robot_base_frame: r1/base_footprint
update_frequency: 20.0
publish_frequency: 20.0
rolling_window: true
always_send_full_costmap: true
static_map: false
width: 5.0
height: 5.0
resolution: 0.05
plugins:
  - {name: obstacles, type: "costmap_2d::ObstacleLayer"}
obstacles:
  observation_sources: scan
  scan: {data_type: LaserScan, sensor_frame: r1/base_footprint, clearing: true, marking: true, topic: scan}